---
development:
  checkpoint:
    session: 'god'
    host: 'checkpoint.dev'

test:
  checkpoint:
    session: 'checkpoint'
    host: 'checkpoint.dev'
  elasticsearch:
    host: 'localhost:9200'

staging:
  checkpoint:
    session: 'abc'
    host: 'pebbles.staging.o5.dev'
  elasticsearch:
    host: 'localhost:9200'

production:
  checkpoint:
    session: 'abc'
    host: 'pebbles.o5.no'
  elasticsearch:
    host: 'localhost:9200'
